### ISSUE TITLE
"Tags" and "Releases" are missing

### ISSUE THREAD

**Issue by Neustradamus** [webmin/usermin#59]
"Tags" and "Releases" are missing:
- https://github.com/webmin/usermin/tags
- https://github.com/webmin/usermin/releases

There are for Webmin:
- https://github.com/webmin/webmin/tags
- https://github.com/webmin/webmin/releases

**Comment by Neustradamus** [comment]
Ping @jcameron.

Example with last current Webmin: "1.954":
- https://github.com/webmin/webmin/commit/e1219d58cf2135aa503045c778509ac6f36962d0 = https://github.com/webmin/webmin/releases/tag/1.954

**Comment by swelljoe** [comment]
Jamie's release process doesn't go through github, they go to SourceForge. I'm surprised Webmin has tagged releases.

**Comment by Neustradamus** [comment]
Dear @swelljoe: It is same for all repositories from https://github.com/virtualmin.

The only one missing is usermin.

I know that you like close all my tickets without solution.

**Comment by swelljoe** [comment]
Virtualmin repos are maintained by me, and I do use github tagging (but not the release system...it's just an accident we have Releases...we probably shouldn't, as the tarballs and zip files don't make sense...they won't work for anything).

So, I'll stop making Releases and instead just tag them from now on. I don't want people getting the impression we release through github. We have yum/apt repos and wbm packages for that.

**Comment by Neustradamus** [comment]
@swelljoe: No no no, it is good for Virtualmin...

**Comment by swelljoe** [comment]
I don't understand why? The release system auto-builds a tarball and a zip file directly from the git repo directory, but they aren't useful for anything. No one should download them. If they want the github repo, they should clone it. If they want to install it, they should get the appropriate package from our software repos. There is not scenario where we would send someone to download those "releases" because they aren't actually our releases meant for installation. It was a mistake to ever make them releases rather than just tags.

**Comment by jcameron** [comment]
I can start tagging releases in Github for Usermin as well as Webmin - it will be handy for us to be able to do minor releases in future.

**Comment by swelljoe** [comment]
Yeah, tagging it great, releases not so much, though I guess for Webmin and Usermin they will work like the regular tarball releases, but with extra cruft.
